# Generated by Django 2.1.5 on 2019-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subrediti',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
