# Generated by Django 2.1.5 on 2019-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_auto_20190114_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='vote_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
