# Generated by Django 2.1.5 on 2019-01-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0004_auto_20190114_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrediti',
            name='slug',
            field=models.SlugField(),
        ),
    ]
